version: '2'
services:
  web:
    build: .
    container_name: "docker-test-web"
    image: "shahmirj/docker-test"
    ports:
      - "1337:5000"
    volumes:
      - .:/code
    depends_on:
    - redis
  redis:
    container_name: "docker-test-redis"
    image: redis
